# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94aa168b62b9b3872178ad445f03f142d9fc31dbd51fcd5bbfbe93520535a798eb32736ad97a083d4a8f6f5ea9300112e4653800feaf299dab37a708c98dec2f

test:
  secret_key_base: a1a5f3dc590272579feef6cd070413f4f016d67f3ae8c32c13affa54785ce047532cd6814223aa09415ccdaa3bdea26b77958e000a85c52312c0cc70e7372580

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
